GOLD_STANDARDS = {
    "level1": {
        "title": "Start/Stop Latching Circuit",
        "role":  "Automation Technician \u2013 Tier 1",
        "milestones": [
            {"id": "m1", "label": "Observed START pulse (I0 momentary NO)", "weight": 15},
            {"id": "m2", "label": "Motor latched ON after START released",   "weight": 25},
            {"id": "m3", "label": "Observed STOP NC contact opening",        "weight": 15},
            {"id": "m4", "label": "Motor dropped out on STOP",               "weight": 25},
            {"id": "m5", "label": "Full start-run-stop cycle completed",     "weight": 20},
        ],
        "efficiency_thresholds": {"exceptional": 300, "proficient": 600, "satisfactory": 1200, "poor": 2400},
        "bonus_criteria": [],
    },
    "level2": {
        "title": "Tank Filling System",
        "role":  "Process Control Technician \u2013 Tier 1",
        "milestones": [
            {"id": "m1", "label": "Pump started at low level (LS_LOW open)",    "weight": 20},
            {"id": "m2", "label": "Pump latched via seal circuit",               "weight": 20},
            {"id": "m3", "label": "Pump stopped at high level (LS_HIGH closed)", "weight": 20},
            {"id": "m4", "label": "Tank drained and auto-cycle restarted",       "weight": 20},
            {"id": "m5", "label": "All fault injection tests completed",         "weight": 20},
        ],
        "efficiency_thresholds": {"exceptional": 600, "proficient": 1200, "satisfactory": 2400, "poor": 4800},
        "bonus_criteria": [{"key": "fault_tested", "label": "Fault injection tested", "points": 5}],
    },
    "level3": {
        "title": "Modbus TCP Communication",
        "role":  "Industrial Networks Technician \u2013 Tier 2",
        "milestones": [
            {"id": "m1", "label": "FC03 - Read holding registers",      "weight": 15},
            {"id": "m2", "label": "FC01 - Read coils",                  "weight": 10},
            {"id": "m3", "label": "FC05 - Write single coil",           "weight": 15},
            {"id": "m4", "label": "FC06 - Write single register",       "weight": 15},
            {"id": "m5", "label": "FC04 - Read input registers",        "weight": 10},
            {"id": "m6", "label": "FC16 - Write multiple registers",    "weight": 20},
            {"id": "m7", "label": "MBAP header inspected on 5+ frames", "weight": 15},
        ],
        "efficiency_thresholds": {"exceptional": 20, "proficient": 40, "satisfactory": 80, "poor": 160},
        "bonus_criteria": [{"key": "all_fc", "label": "All 7 function codes used", "points": 5}],
    },
    "level4": {
        "title": "Safety Interlock \u2014 Drill Machine",
        "role":  "Functional Safety Engineer \u2013 IEC 62061",
        "milestones": [
            {"id": "m1", "label": "E-Stop tripped and drill stopped",          "weight": 15},
            {"id": "m2", "label": "Gate guard opened and drill stopped",       "weight": 15},
            {"id": "m3", "label": "RESET acknowledged after E-Stop",          "weight": 15},
            {"id": "m4", "label": "Dual-channel safety OK, drill running",     "weight": 20},
            {"id": "m5", "label": "E-Stop released mid-cycle",                "weight": 10},
            {"id": "m6", "label": "Recovery: release E-Stop + RESET + START", "weight": 15},
            {"id": "m7", "label": "Wire break fault - fail-safe shutdown",     "weight": 10},
        ],
        "efficiency_thresholds": {"exceptional": 500, "proficient": 1000, "satisfactory": 2000, "poor": 4000},
        "bonus_criteria": [{"key": "wire_break", "label": "Wire break fault simulated", "points": 5}],
    },
    "level5": {
        "title": "Timed Conveyor \u2014 TON Instruction",
        "role":  "Automation Technician \u2013 Tier 2",
        "milestones": [
            {"id": "m1", "label": "First box detected and timer started",    "weight": 10},
            {"id": "m2", "label": "Conveyor ran for timed cycle",            "weight": 15},
            {"id": "m3", "label": "Timer DN bit fired",                      "weight": 15},
            {"id": "m4", "label": "E-Stop reset timer to zero mid-cycle",    "weight": 20},
            {"id": "m5", "label": "Timer preset modified and re-tested",     "weight": 15},
            {"id": "m6", "label": "Changed preset time and completed cycle", "weight": 15},
            {"id": "m7", "label": "5 boxes packed total",                    "weight": 10},
        ],
        "efficiency_thresholds": {"exceptional": 500, "proficient": 1000, "satisfactory": 2000, "poor": 4000},
        "bonus_criteria": [{"key": "estop_mid", "label": "E-Stop tested mid-cycle", "points": 5}],
    },
    "level6": {
        "title": "Sequential Batching \u2014 State Machine",
        "role":  "Process Automation Engineer \u2013 ISA-88",
        "milestones": [
            {"id": "m1", "label": "FILLING state entered (pump ON)",                   "weight": 15},
            {"id": "m2", "label": "MIXING state entered (agitator ON, timer started)", "weight": 15},
            {"id": "m3", "label": "DRAINING state entered (drain valve open)",         "weight": 15},
            {"id": "m4", "label": "Full batch cycle completed (back to IDLE)",         "weight": 20},
            {"id": "m5", "label": "Mix timer elapsed correctly",                       "weight": 10},
            {"id": "m6", "label": "E-Stop abort tested mid-batch",                    "weight": 15},
            {"id": "m7", "label": "Auto-cycle completed 2+ batches",                  "weight": 10},
        ],
        "efficiency_thresholds": {"exceptional": 800, "proficient": 1600, "satisfactory": 3200, "poor": 6400},
        "bonus_criteria": [
            {"key": "estop_abort", "label": "E-Stop abort mid-batch tested",   "points": 5},
            {"key": "autocycle",   "label": "Auto-cycle ran multiple batches", "points": 5},
        ],
    },
}
