# Generated by Django 5.2.15 on 2026-08-01 15:11

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeLogEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Password change log',
                'verbose_name_plural': 'Password change log',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
