# Generated by Django 5.2.17 on 2026-08-23 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_key', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('tier_label', models.CharField(max_length=50)),
                ('milestones_done', models.IntegerField()),
                ('milestones_total', models.IntegerField()),
                ('efficiency_label', models.CharField(max_length=50)),
                ('bonus_earned', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
