# Generated by Django 5.2.15 on 2026-07-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_key', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('tier_label', models.CharField(max_length=100)),
                ('milestones_done', models.IntegerField()),
                ('milestones_total', models.IntegerField()),
                ('efficiency_label', models.CharField(max_length=100)),
                ('bonus_earned', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('challenge', 'Challenge'), ('lesson', 'Lesson'), ('tool', 'Tool')], max_length=20)),
                ('html_file', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_title', models.CharField(blank=True, max_length=200, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GradeDescriptor',
            fields=[
                ('grade', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('min_score', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='EfficiencyThreshold',
            fields=[
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='efficiency_thresholds', serialize=False, to='assessment.module')),
                ('exceptional', models.IntegerField()),
                ('proficient', models.IntegerField()),
                ('satisfactory', models.IntegerField()),
                ('poor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BonusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=300)),
                ('points', models.IntegerField(default=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_criteria', to='assessment.module')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=500)),
                ('weight', models.IntegerField(default=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='assessment.module')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('variant', models.CharField(choices=[('default', 'Default'), ('warn', 'Warning'), ('danger', 'Danger'), ('good', 'Good'), ('purple', 'Purple')], default='default', max_length=20)),
                ('tip_text', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='assessment.module')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
