# Generated by Django 5.2.15 on 2026-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_add_user_to_assessment_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='token_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
